import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Lustiq Platform - Dashboard',
};

export default function Page() {

  return (
	<main className={'page_content'}>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>	
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>	
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>
			<p>&nbsp;1</p>				
			<p>&nbsp;1</p>									
		</main>    
  );
}